-
  location: :queen_kaahumanu
  times:
  - '7:00'
  - '8:00'
  - '9:00'
  - '10:00'
  - '11:00'
  - '12:00'
  - '13:00'
  - '14:00'
  - '15:00'
  - '16:00'
  - '17:00'
  - '18:00'
  - '19:00'
  - '20:00'
  - '21:00'
  name: Queen Kaahumanu Mall
  true_location: queen_kaahumanu
-
  location: :kahului_shopping_center
  times:
  - '7:08'
  - '8:08'
  - '9:08'
  - '10:08'
  - '11:08'
  - '12:08'
  - '13:08'
  - '14:08'
  - '15:08'
  - '16:08'
  - '17:08'
  - '18:08'
  - '19:08'
  - '20:08'
  - '21:08'
  name: Kahului Shopping Center
  true_location: kahului_shopping_center
-
  location: :kahului_safeway
  times:
  - '7:10'
  - '8:10'
  - '9:10'
  - '10:10'
  - '11:10'
  - '12:10'
  - '13:10'
  - '14:10'
  - '15:10'
  - '16:10'
  - '17:10'
  - '18:10'
  - '19:10'
  - '20:10'
  - '21:10'
  name: Safeway / Ross
  true_location: kahului_safeway
-
  location: :kmart
  times:
  - '7:16'
  - '8:16'
  - '9:16'
  - '10:16'
  - '11:16'
  - '12:16'
  - '13:16'
  - '14:16'
  - '15:16'
  - '16:16'
  - '17:16'
  - '18:16'
  - '19:16'
  - '20:16'
  - '21:16'
  name: K-Mart
  true_location: kmart
-
  location: :maui_market_place
  times:
  - '7:25'
  - '8:25'
  - '9:25'
  - '10:25'
  - '11:25'
  - '12:25'
  - '13:25'
  - '14:25'
  - '15:25'
  - '16:25'
  - '17:25'
  - '18:25'
  - '19:25'
  - '20:25'
  - '21:25'
  name: Maui Marketplace Food Court
  true_location: maui_market_place
-
  location: :walmart_across
  times:
  - '7:29'
  - '8:29'
  - '9:29'
  - '10:29'
  - '11:29'
  - '12:29'
  - '13:29'
  - '14:29'
  - '15:29'
  - '16:29'
  - '17:29'
  - '18:29'
  - '19:29'
  - '20:29'
  - '21:29'
  name: Pakaula St. / Wal-Mart back Entrance
  true_location: walmart
  destination: true
-
  location: :west_papa_lanai_st_across
  times:
  - '7:34'
  - '8:34'
  - '9:34'
  - '10:34'
  - '11:34'
  - '12:34'
  - '13:34'
  - '14:34'
  - '15:34'
  - '16:34'
  - '17:34'
  - '18:34'
  - '19:34'
  - '20:34'
  - '21:34'
  name: W. Papa Ave. / S Lanai St.
  true_location: west_papa_lanai_st
-
  location: :west_papa_laau_st_across
  times:
  - '7:35'
  - '8:35'
  - '9:35'
  - '10:35'
  - '11:35'
  - '12:35'
  - '13:35'
  - '14:35'
  - '15:35'
  - '16:35'
  - '17:35'
  - '18:35'
  - '19:35'
  - '20:35'
  - '21:35'
  name: W. Papa Ave. / Laau St.
  true_location: west_papa_laau_st
-
  location: :luana_gardens_across
  times:
  - '7:37'
  - '8:37'
  - '9:37'
  - '10:37'
  - '11:37'
  - '12:37'
  - '13:37'
  - '14:37'
  - '15:37'
  - '16:37'
  - '17:37'
  - '18:37'
  - '19:37'
  - '20:37'
  - '21:37'
  name: Luana Gardens
  true_location: luana_gardens
-
  location: :kamehameha_ave_molokai_akua_st_across
  times:
  - '7:38'
  - '8:38'
  - '9:38'
  - '10:38'
  - '11:38'
  - '12:38'
  - '13:38'
  - '14:38'
  - '15:38'
  - '16:38'
  - '17:38'
  - '18:38'
  - '19:38'
  - '20:38'
  - '21:38'
  name: Kamehameha Ave. / Molokai Akua St.
  true_location: kamehameha_ave_molokai_akua_st
-
  location: :kamehameha_ave_laau_st_across
  times:
  - '7:39'
  - '8:39'
  - '9:39'
  - '10:39'
  - '11:39'
  - '12:39'
  - '13:39'
  - '14:39'
  - '15:39'
  - '16:39'
  - '17:39'
  - '18:39'
  - '19:39'
  - '20:39'
  - '21:39'
  name: Kamehameha Ave. / Laau St.
  true_location: kamehameha_ave_laau_st
-
  location: :hale_mahaolu_elua
  times:
  - '7:40'
  - '8:40'
  - '9:40'
  - '10:40'
  - '11:40'
  - '12:40'
  - '13:40'
  - '14:40'
  - '15:40'
  - '16:40'
  - '17:40'
  - '18:40'
  - '19:40'
  - '20:40'
  - '21:40'
  name: Hale Mahaolu Elua
  true_location: hale_mahaolu_elua
-
  location: :kahului_community_center_across
  times:
  - '7:42'
  - '8:42'
  - '9:42'
  - '10:42'
  - '11:42'
  - '12:42'
  - '13:42'
  - '14:42'
  - '15:42'
  - '16:42'
  - '17:42'
  - '18:42'
  - '19:42'
  - '20:42'
  - '21:42'
  name: Kahului Community Center
  true_location: kahului_community_center
-
  location: :onehee_papa_ave_across
  times:
  - '7:43'
  - '8:43'
  - '9:43'
  - '10:43'
  - '11:43'
  - '12:43'
  - '13:43'
  - '14:43'
  - '15:43'
  - '16:43'
  - '17:43'
  - '18:43'
  - '19:43'
  - '20:43'
  - '21:43'
  name: Onehee / S. Papa Ave.
  true_location: onehee_papa_ave
-
  location: :papa_ave_kea_across
  times:
  - '7:44'
  - '8:44'
  - '9:44'
  - '10:44'
  - '11:44'
  - '12:44'
  - '13:44'
  - '14:44'
  - '15:44'
  - '16:44'
  - '17:44'
  - '18:44'
  - '19:44'
  - '20:44'
  - '21:44'
  name: Papa Ave. / Kea St.
  true_location: papa_ave_kea
-
  location: :roselani_place_across
  times:
  - '7:45'
  - '8:45'
  - '9:45'
  - '10:45'
  - '11:45'
  - '12:45'
  - '13:45'
  - '14:45'
  - '15:45'
  - '16:45'
  - '17:45'
  - '18:45'
  - '19:45'
  - '20:45'
  - '21:45'
  name: Roselani Place
  true_location: roselani_place
-
  location: :maui_college
  times:
  - '7:48'
  - '8:48'
  - '9:48'
  - '10:48'
  - '11:48'
  - '12:48'
  - '13:48'
  - '14:48'
  - '15:48'
  - '16:48'
  - '17:48'
  - '18:48'
  - '19:48'
  - '20:48'
  - '21:48'
  name: Harbor Lights / UH Maui College
  true_location: maui_college
-
  location: :queen_kaahumanu
  times:
  - '8:00'
  - '9:00'
  - '10:00'
  - '11:00'
  - '12:00'
  - '13:00'
  - '14:00'
  - '15:00'
  - '16:00'
  - '17:00'
  - '18:00'
  - '19:00'
  - '20:00'
  - '21:00'
  - '22:00'
  name: Queen Kaahumanu Mall
  true_location: queen_kaahumanu
