-
  times:
  - '6:15'
  location: :kilohana_south_kihei
-
  location: :mana_kai_resort_south
  times:
  - '6:16'
-
  location: :kamaole_beach_3
  times:
  - '6:18'
-
  location: :kamaole_shopping_center
  times:
  - '6:19'
-
  location: :kamaole_beach_1
  times:
  - '6:21'
-
  location: :walaka_south_kihei
  times:
  - '6:22'
-
  location: :keala_place_south_kihei
  times:
  - '6:23'
-
  location: :welakahao_south_kihei
  times:
  - '6:24'
-
  location: :st_theresas_church
  times:
  - '6:25'
-
  location: :kihei_aquatics_center
  times:
  - '6:27'
-
  location: :waipuilani_south_kihei_makai
  times:
  - '6:33'
-
  location: :kulanihakoi_south_kihei
  times:
  - '6:34'
-
  location: :kaonoulu_south_kihei_makai
  times:
  - '6:36'
-
  location: :ohukai_south_kihei
  times:
  - '6:38'
-
  location: :uwapo_south_kihei_mauka
  times:
  - '6:40'
-
  location: :kaanapali_sheraton
  times:
  - '7:15'
-
  location: :kaanapali_beach_hotel
  times:
  - '7:16'
-
  location: :kaanapali_westin
  times:
  - '7:17'
-
  location: :kaanapali_alii
  times:
  - '7:18'
-
  location: :kaanapali_marriot
  times:
  - '7:19'
-
  location: :kaanapali_hyatt_regency
  times:
  - '7:20'
-
  location: :maui_eldorado
  times:
  - '7:24'
-
  location: :napili_shores
  times:
  - '7:35'
-
  location: :napili_kai
  times:
  - '7:37'
-
  location: :ritz_carlton
  times:
  - '7:45'
-
  location: :ritz_carlton
  times:
  - '16:05'
-
  location: :napili_kai
  times:
  - '16:15'
-
  location: :napili_shores
  times:
  - '16:17'
-
  location: :maui_eldorado
  times:
  - '16:30'
-
  location: :kaanapali_sheraton
  times:
  - '16:35'
-
  location: :kaanapali_beach_hotel
  times:
  - '16:36'
-
  location: :kaanapali_westin
  times:
  - '16:37'
-
  location: :kaanapali_alii
  times:
  - '16:38'
-
  location: :kaanapali_marriot
  times:
  - '16:39'
-
  location: :kaanapali_hyatt_regency
  times:
  - '16:40'
-
  location: :uwapo_south_kihei_mauka
  times:
  - '17:19'
-
  location: :ohukai_south_kihei
  times:
  - '17:20'
-
  location: :kaonoulu_south_kihei_makai
  times:
  - '17:22'
-
  location: :kulanihakoi_south_kihei
  times:
  - '17:23'
-
  location: :waipuilani_south_kihei_makai
  times:
  - '17:24'
-
  location: :kihei_aquatics_center
  times:
  - '17:26'
-
  location: :st_theresas_church
  times:
  - '17:29'
-
  location: :welakahao_south_kihei
  times:
  - '17:30'
-
  location: :keala_place_south_kihei
  times:
  - '17:31'
-
  location: :walaka_south_kihei
  times:
  - '17:32'
-
  location: :kamaole_beach_1
  times:
  - '17:33'
-
  location: :kamaole_shopping_center
  times:
  - '17:34'
-
  location: :kamaole_beach_3
  times:
  - '17:35'
-
  location: :mana_kai_resort_south
  times:
  - '17:37'
-
  location: :kilohana_south_kihei
  times:
  - '17:38'













