-
  location: :queen_kaahumanu
  times:
  - '7:00'
  - '8:00'
  - '9:00'
  - '10:00'
  - '11:00'
  - '12:00'
  - '13:00'
  - '14:00'
  - '15:00'
  - '16:00'
  - '17:00'
  - '18:00'
  - '19:00'
  - '20:00'
  - '21:00'
  name: Queen Kaahumanu Mall
  true_location: queen_kaahumanu
-
  location: :kanaloa_baseball_field
  times:
  - '7:03'
  - '8:03'
  - '9:03'
  - '10:03'
  - '11:03'
  - '12:03'
  - '13:03'
  - '14:03'
  - '15:03'
  - '16:03'
  - '17:03'
  - '18:03'
  - '19:03'
  - '20:03'
  - '21:03'
  name: Kanaloa Ave. / Little League Field
  true_location: kanaloa_baseball_field
-
  location: :wailuku_ymca
  times:
  - '7:04'
  - '8:04'
  - '9:04'
  - '10:04'
  - '11:04'
  - '12:04'
  - '13:04'
  - '14:04'
  - '15:04'
  - '16:04'
  - '17:04'
  - '18:04'
  - '19:04'
  - '20:04'
  - '21:04'
  name: YMCA - Mikohu Loop / Kanaloa Ave.
  true_location: wailuku_ymca
-
  location: :lihi_kanaloa_ave_parkside
  times:
  - '7:06'
  - '8:06'
  - '9:06'
  - '10:06'
  - '11:06'
  - '12:06'
  - '13:06'
  - '14:06'
  - '15:06'
  - '16:06'
  - '17:06'
  - '18:06'
  - '19:06'
  - '20:06'
  - '21:06'
  name: Lihi St. / Kanaloa Ave. (Parkside)
  true_location: lihi_kanaloa_ave
-
  location: :liholiho_kanaloa_ave_parkside
  times:
  - '7:07'
  - '8:07'
  - '9:07'
  - '10:07'
  - '11:07'
  - '12:07'
  - '13:07'
  - '14:07'
  - '15:07'
  - '16:07'
  - '17:07'
  - '18:07'
  - '19:07'
  - '20:07'
  - '21:07'
  name: Liholiho St. / Kanaloa Ave. (Parkside)
  true_location: liholiho_kanaloa_ave
-
  location: :wailuku_community_center_across
  times:
  - '7:08'
  - '8:08'
  - '9:08'
  - '10:08'
  - '11:08'
  - '12:08'
  - '13:08'
  - '14:08'
  - '15:08'
  - '16:08'
  - '17:08'
  - '18:08'
  - '19:08'
  - '20:08'
  - '21:08'
  name: Wailuku Community Center
  true_location: wailuku_community_center
-
  location: :eha_st_sack_n_save
  times:
  - '7:11'
  - '8:11'
  - '9:11'
  - '10:11'
  - '11:11'
  - '12:11'
  - '13:11'
  - '14:11'
  - '15:11'
  - '16:11'
  - '17:11'
  - '18:11'
  - '19:11'
  - '20:11'
  - '21:11'
  name: Eha St. - In Front Sack N Save
  true_location: eha_st_sack_n_save
-
  location: :hawaiian_homes_makai
  times:
  - '7:15'
  - '8:15'
  - '9:15'
  - '10:15'
  - '11:15'
  - '12:15'
  - '13:15'
  - '14:15'
  - '15:15'
  - '16:15'
  - '17:15'
  - '18:15'
  - '19:15'
  - '20:15'
  - '21:15'
  name: Hawaiian Homes (Makai)
  true_location: hawaiian_homes
-
  location: :waiehu_heights_aukai
  times:
  - '7:16'
  - '8:16'
  - '9:16'
  - '10:16'
  - '11:16'
  - '12:16'
  - '13:16'
  - '14:16'
  - '15:16'
  - '16:16'
  - '17:16'
  - '18:16'
  - '19:16'
  - '20:16'
  - '21:16'
  name: Waiehu Heights / Aukai Place
  true_location: waiehu_heights_aukai
  destination: true
-
  location: :waiehu_heights_wailupe
  times:
  - '7:17'
  - '8:17'
  - '9:17'
  - '10:17'
  - '11:17'
  - '12:17'
  - '13:17'
  - '14:17'
  - '15:17'
  - '16:17'
  - '17:17'
  - '18:17'
  - '19:17'
  - '20:17'
  - '21:17'
  name: Waiehu Heights / Wailupe Drive
  true_location: waiehu_heights_wailupe
-
  location: :makaala_hale_mahaolu
  times:
  - '7:19'
  - '8:19'
  - '9:19'
  - '10:19'
  - '11:19'
  - '12:19'
  - '13:19'
  - '14:19'
  - '15:19'
  - '16:19'
  - '17:19'
  - '18:19'
  - '19:19'
  - '20:19'
  - '21:19'
  name: Makaala Drive - In Front Hale Mahaolu
  true_location: makaala_hale_mahaolu
-
  location: :makaala_kilihau_st
  times:
  - '7:20'
  - '8:20'
  - '9:20'
  - '10:20'
  - '11:20'
  - '12:20'
  - '13:20'
  - '14:20'
  - '15:20'
  - '16:20'
  - '17:20'
  - '18:20'
  - '19:20'
  - '20:20'
  - '21:20'
  name: Makaala Drive / Kilihau St.
  true_location: makaala_kilihau_st
-
  location: :makaala_kuhio_pl
  times:
  - '7:22'
  - '8:22'
  - '9:22'
  - '10:22'
  - '11:22'
  - '12:22'
  - '13:22'
  - '14:22'
  - '15:22'
  - '16:22'
  - '17:22'
  - '18:22'
  - '19:22'
  - '20:22'
  - '21:22'
  name: Makaala Drive / Kuhio Place
  true_location: makaala_kuhio_pl
-
  location: :makaala_makamua_st_across
  times:
  - '7:23'
  - '8:23'
  - '9:23'
  - '10:23'
  - '11:23'
  - '12:23'
  - '13:23'
  - '14:23'
  - '15:23'
  - '16:23'
  - '17:23'
  - '18:23'
  - '19:23'
  - '20:23'
  - '21:23'
  name: Makaala Drive / Makamua St.
  true_location: makaala_makamua_st
-
  location: :piihana_terrace
  times:
  - '7:24'
  - '8:24'
  - '9:24'
  - '10:24'
  - '11:24'
  - '12:24'
  - '13:24'
  - '14:24'
  - '15:24'
  - '16:24'
  - '17:24'
  - '18:24'
  - '19:24'
  - '20:24'
  - '21:24'
  name: Pi'ihana Terrace
  true_location: piihana_terrace
-
  location: :kahekili_terrace
  times:
  - '7:26'
  - '8:26'
  - '9:26'
  - '10:26'
  - '11:26'
  - '12:26'
  - '13:26'
  - '14:26'
  - '15:26'
  - '16:26'
  - '17:26'
  - '18:26'
  - '19:26'
  - '20:26'
  - '21:26'
  name: Kahekili Terrace
  true_location: kahekili_terrace
-
  location: :wailuku_post_office
  times:
  - '7:29'
  - '8:29'
  - '9:29'
  - '10:29'
  - '11:29'
  - '12:29'
  - '13:29'
  - '14:29'
  - '15:29'
  - '16:29'
  - '17:29'
  - '18:29'
  - '19:29'
  - '20:29'
  - '21:29'
  name: Wailuku Post Office
  true_location: wailuku_post_office
-
  location: :ke_ola_health_clinic
  times:
  - '7:32'
  - '8:32'
  - '9:32'
  - '10:32'
  - '11:32'
  - '12:32'
  - '13:32'
  - '14:32'
  - '15:32'
  - '16:32'
  - '17:32'
  - '18:32'
  - '19:32'
  - '20:32'
  - '21:32'
  name: Malama I Ke Ola Health Clinic
  true_location: ke_ola_health_clinic
-
  location: :kamole_st_kehalani_sub
  times:
  - '7:35'
  - '8:35'
  - '9:35'
  - '10:35'
  - '11:35'
  - '12:35'
  - '13:35'
  - '14:35'
  - '15:35'
  - '16:35'
  - '17:35'
  - '18:35'
  - '19:35'
  - '20:35'
  - '21:35'
  name: Kamole Street / Kehalani Subdivision
  true_location: kamole_st_kehalani_sub
-
  location: :ka_hale_ake_ola
  times:
  - '7:37'
  - '8:37'
  - '9:37'
  - '10:37'
  - '11:37'
  - '12:37'
  - '13:37'
  - '14:37'
  - '15:37'
  - '16:37'
  - '17:37'
  - '18:37'
  - '19:37'
  - '20:37'
  - '21:37'
  name: Ka Hale A Ke Ola
  true_location: ka_hale_ake_ola
-
  location: :state_bldg
  times:
  - '7:43'
  - '8:43'
  - '9:43'
  - '10:43'
  - '11:43'
  - '12:43'
  - '13:43'
  - '14:43'
  - '15:43'
  - '16:43'
  - '17:43'
  - '18:43'
  - '19:43'
  - '20:43'
  - '21:43'
  name: State Office Building
  true_location: state_bldg
-
  location: :maui_lani_parkway
  times:
  - '7:46'
  - '8:46'
  - '9:46'
  - '10:46'
  - '11:46'
  - '12:46'
  - '13:46'
  - '14:46'
  - '15:46'
  - '16:46'
  - '17:46'
  - '18:46'
  - '19:46'
  - '20:46'
  - '21:46'
  name: Maui Lani Parkway
  true_location: maui_lani_parkway
-
  location: :maui_memorial_hospital_across
  times:
  - '7:49'
  - '8:49'
  - '9:49'
  - '10:49'
  - '11:49'
  - '12:49'
  - '13:49'
  - '14:49'
  - '15:49'
  - '16:49'
  - '17:49'
  - '18:49'
  - '19:49'
  - '20:49'
  - '21:49'
  name: Maui Memorial Hospital (Across)
  true_location: maui_memorial_hospital
-
  location: :queen_kaahumanu
  times:
  - '8:00'
  - '9:00'
  - '10:00'
  - '11:00'
  - '12:00'
  - '13:00'
  - '14:00'
  - '15:00'
  - '16:00'
  - '17:00'
  - '18:00'
  - '19:00'
  - '20:00'
  - '21:00'
  - '22:00'
  name: Queen Kaahumanu Mall
  true_location: queen_kaahumanu
