-
  times:
  - '5:30'
  location: :haiku_community_center
-
  times:
  - '5:40'
  location: :paia_community_center
-
  times:
  - '6:00'
  location: :war_memorial
-
  times:
  - '6:10'
  location: :kuihelani_park_ride
-
  times:
  - '6:25'
  location: :piilani_shopping_center
-
  location: :andaz_wailea
  times:
  - '6:37'
-
  location: :wailea_marriot
  times:
  - '6:40'
-
  location: :grand_wailea
  times:
  - '6:41'
-
  location: :four_seasons
  times:
  - '6:43'
-
  location: :hotel_wailea
  times:
  - '6:45'
-
  times:
  - '7:00'
  location: :makena
  destination: true
-
  times:
  - '16:15'
  location: :makena
  name: Makena
-
  location: :hotel_wailea
  times:
  - '16:30'
-
  location: :four_seasons
  times:
  - '16:32'
-
  location: :grand_wailea
  times:
  - '16:35'
-
  location: :wailea_marriot
  times:
  - '16:36'
-
  location: :andaz_wailea
  times:
  - '16:37'
-
  times:
  - '16:55'
  location: :piilani_shopping_center
-
  times:
  - '17:15'
  location: :kuihelani_park_ride
-
  times:
  - '17:30'
  location: :war_memorial
-
  times:
  - '17:50'
  location: :paia_community_center
-
  times:
  - '18:00'
  location: :haiku_community_center
