-
  location: :queen_kaahumanu
  times:
  - '5:30'
  - '7:00'
  - '8:30'
  - '10:00'
  - '11:30'
  - '13:00'
  - '14:30'
  - '16:00'
  - '17:30'
  - '19:00'
  - '20:30'
  name: Queen Kaahumanu Mall
  true_location: queen_kaahumanu
-
  location: :kahului_salvation_army
  times:
  - '5:33'
  - '7:03'
  - '8:33'
  - '10:03'
  - '11:33'
  - '13:03'
  - '14:33'
  - '16:03'
  - '17:33'
  - '19:03'
  - '20:33'
  name: Salvation Army
  true_location: kahului_salvation_army
-
  location: :kahului_safeway
  times:
  - '5:34'
  - '7:04'
  - '8:34'
  - '10:04'
  - '11:34'
  - '13:04'
  - '14:34'
  - '16:04'
  - '17:34'
  - '19:04'
  - '20:34'
  name: Safeway
  true_location: kahului_safeway
-
  location: :kahului_airport
  times:
  - '5:40'
  - '7:10'
  - '8:40'
  - '10:10'
  - '11:40'
  - '13:10'
  - '14:40'
  - '16:10'
  - '17:40'
  - '19:10'
  - '20:40'
  name: 'Airport Pick-up Zone #3'
  true_location: kahului_airport
-
  location: :paia_entrance
  times:
  - '5:53'
  - '7:23'
  - '8:53'
  - '10:23'
  - '11:53'
  - '13:23'
  - '14:53'
  - '16:23'
  - '17:53'
  - '19:23'
  - '20:53'
  name: Paia Town - Entrance on Baldwin Side
  true_location: paia_entrance
-
  location: :paia_charleys
  times:
  - '5:54'
  - '7:24'
  - '8:54'
  - '10:24'
  - '11:54'
  - '13:24'
  - '14:54'
  - '16:24'
  - '17:54'
  - '19:24'
  - '20:54'
  name: Paia Town - Before Charleys
  true_location: paia_charleys
-
  location: :kuau_mart
  times:
  - '5:56'
  - '7:26'
  - '8:56'
  - '10:26'
  - '11:56'
  - '13:26'
  - '14:56'
  - '16:26'
  - '17:56'
  - '19:26'
  - '20:56'
  name: Kuau Mart
  true_location: kuau_mart
-
  location: :haiku_marketplace
  times:
  - '6:11'
  - '7:41'
  - '9:11'
  - '10:41'
  - '12:11'
  - '13:41'
  - '15:11'
  - '16:41'
  - '18:11'
  - '19:41'
  - '21:11'
  name: Haiku Marketplace
  true_location: haiku_marketplace
  destination: true
-
  location: :haiku_community_center
  times:
  - '6:17'
  - '7:47'
  - '9:17'
  - '10:47'
  - '12:17'
  - '13:47'
  - '15:17'
  - '16:47'
  - '18:17'
  - '19:47'
  - '21:17'
  name: Shelter Next to Haiku Community Center
  true_location: haiku_community_center
-
  location: :kuau_mart
  times:
  - '6:26'
  - '7:56'
  - '9:26'
  - '10:56'
  - '12:26'
  - '13:56'
  - '15:26'
  - '16:56'
  - '18:26'
  - '19:56'
  - '21:26'
  name: Kuau Mart
  true_location: kuau_mart
-
  location: :paia_charleys
  times:
  - '6:29'
  - '7:59'
  - '9:29'
  - '10:59'
  - '12:29'
  - '13:59'
  - '15:29'
  - '16:59'
  - '18:29'
  - '19:59'
  - '21:29'
  name: Paia Town - Before Charleys
  true_location: paia_charleys
-
  location: :paia_entrance
  times:
  - '6:30'
  - '8:00'
  - '9:30'
  - '11:00'
  - '12:30'
  - '14:00'
  - '15:30'
  - '17:00'
  - '18:30'
  - '20:00'
  - '21:30'
  name: Paia Town - Entrance on Baldwin Side
  true_location: paia_entrance
-
  location: :kahului_airport
  times:
  - '6:43'
  - '8:13'
  - '9:43'
  - '11:13'
  - '12:43'
  - '14:13'
  - '15:43'
  - '17:13'
  - '18:43'
  - '20:13'
  - '21:43'
  name: 'Airport Pick-up Zone #3'
  true_location: kahului_airport
-
  location: :kahului_safeway_across
  times:
  - '6:47'
  - '8:17'
  - '9:47'
  - '11:17'
  - '12:47'
  - '14:17'
  - '15:47'
  - '17:17'
  - '18:47'
  - '20:17'
  name: Safeway / Maui Mall Entrance
  true_location: kahului_safeway
-
  location: :kahului_salvation_army
  times:
  - '6:48'
  - '8:18'
  - '9:48'
  - '11:18'
  - '12:48'
  - '14:18'
  - '15:48'
  - '17:18'
  - '18:48'
  - '20:18'
  - ''
  name: Salvation Army
  true_location: kahului_salvation_army
-
  location: :queen_kaahumanu
  times:
  - '7:00'
  - '8:30'
  - '10:00'
  - '11:30'
  - '13:00'
  - '14:30'
  - '16:00'
  - '17:30'
  - '19:00'
  - '20:30'
  - ''
  name: Queen Kaahumanu Mall
  true_location: queen_kaahumanu